# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Collections Lab
tagline:          'UCLA Digital Library'
description:      'Machine-learning and collections as data experiments with digital collections'
url:
baseurl:          /

author:
  name:           'Dawn Childress'
  url:            https://twitter.com/kirschbombe

paginate:         5

#Post excerpt
excerpt_separator: "<!--excerpt-->"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/collectionslab

plugins: [jekyll-paginate]

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
